# -*- coding: utf-8 -*-
"""5.4-importance/correlation plot - w&b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kwWm1iESpnYUiZeg_QyWMnhuKjGDjsPa
"""

import matplotlib.pyplot as plt
import numpy as np

parameters = ["Weight Decay", "Tiempo de entrenamiento", "Transformers Layers", "Projection Dimension", "Learning Rate", "Batch Size", "Patch Size"]
correlations = [0.608, 0.616, 0.786, 0.999, 0.999, 0.999, 0.000]
importance = [0.013, 0.037, 0.093, 0.315, 0.271, 0.271, 0.000]

fig, ax = plt.subplots()

# Convert correlations to a range from 0 to 1 for coloring
correlations_color = [(x+1)/2 for x in correlations]

bars1 = ax.barh([p + " - Correlación" for p in parameters], correlations, color=plt.cm.RdYlGn(correlations_color), edgecolor='black')
bars2 = ax.barh([p + " - Importancia" for p in parameters], importance, color='blue', edgecolor='black')

# Creating color bar
sm = plt.cm.ScalarMappable(cmap=plt.cm.RdYlGn, norm=plt.Normalize(vmin=-1, vmax=1))
cbar = plt.colorbar(sm)
cbar.set_label('Correlación', rotation=270,labelpad=15)

# Creating a second color bar for importance
sm2 = plt.cm.ScalarMappable(cmap=plt.cm.Blues, norm=plt.Normalize(vmin=0, vmax=1))
cbar2 = plt.colorbar(sm2)
cbar2.set_label('Importancia', rotation=270,labelpad=15)

plt.xlabel('Valores')
plt.title('Análisis de hiper-parámetros para la variante macro')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

parameters = ["Weight Decay", "Tiempo de entrenamiento", "Learning Rate", "Batch Size", "Optimizer"]
correlations = [-0.253, 0.577, -0.604, -0.377, 0.605]
importance = [0.366, 0.138, 0.368, 0.003, 0.093]

fig, ax = plt.subplots()

# Convert correlations to a range from 0 to 1 for coloring
correlations_color = [(x+1)/2 for x in correlations]

bars1 = ax.barh([p + " - Correlación" for p in parameters], correlations, color=plt.cm.RdYlGn(correlations_color), edgecolor='black')
bars2 = ax.barh([p + " - Importancia" for p in parameters], importance, color='blue', edgecolor='black')

# Creating color bar
sm = plt.cm.ScalarMappable(cmap=plt.cm.RdYlGn, norm=plt.Normalize(vmin=-1, vmax=1))
cbar = plt.colorbar(sm)
cbar.set_label('Correlación', rotation=270,labelpad=15)

# Creating a second color bar for importance
sm2 = plt.cm.ScalarMappable(cmap=plt.cm.Blues, norm=plt.Normalize(vmin=0, vmax=1))
cbar2 = plt.colorbar(sm2)
cbar2.set_label('Importancia', rotation=270,labelpad=15)

plt.xlabel('Valores')
plt.title('Análisis de hiper-parámetros para la variante micro')

plt.show()